//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.Demo.SmsManagerModule.Application.Models;
using QuickCode.Demo.SmsManagerModule.Domain.Entities;
using QuickCode.Demo.SmsManagerModule.Application.Interfaces.Repositories;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using QuickCode.Demo.SmsManagerModule.Persistence.Contexts;
using QuickCode.Demo.SmsManagerModule.Application.Dtos;

namespace QuickCode.Demo.SmsManagerModule.Persistence.Repositories
{
    public partial class OtpTypesRepository : IOtpTypesRepository
    {
        private readonly WriteDbContext _writeContext;
        private readonly ReadDbContext _readContext;
        private readonly ILogger<OtpTypesRepository> _logger;
        public OtpTypesRepository(ILogger<OtpTypesRepository> logger, WriteDbContext writeContext, ReadDbContext readContext)
        {
            _writeContext = writeContext;
            _readContext = readContext;
            _logger = logger;
        }

        public async Task<DLResponse<OtpTypes>> InsertAsync(OtpTypes value)
        {
            var returnValue = new DLResponse<OtpTypes>(value, "Not Defined");
            try
            {
                await _writeContext.OtpTypes.AddAsync(value);
                await _writeContext.SaveChangesAsync();
                returnValue.Value = value;
            }
            catch (SqlException ex)
            {
                _logger.LogError("{repoName} SqlException {error}", "OtpTypes Insert", ex.Message);
                if (ex.Number.Equals(2627))
                {
                    returnValue.Code = 999;
                    returnValue.Value = value;
                }
                else
                {
                    returnValue.Code = 998;
                    returnValue.Value = value;
                }

                returnValue.Message = ex.ToString();
            }
            catch (Exception ex)
            {
                _logger.LogError("{repoName} Exception {error}", "OtpTypes Insert", ex.Message);
                returnValue.Code = 500;
                returnValue.Value = value;
                returnValue.Message = ex.ToString();
            }

            return returnValue;
        }

        public async Task<DLResponse<bool>> UpdateAsync(OtpTypes value)
        {
            var returnValue = new DLResponse<bool>(false, "Success");
            try
            {
                _writeContext.Set<OtpTypes>().Update(value);
                await _writeContext.SaveChangesAsync();
                returnValue.Value = true;
            }
            catch (SqlException ex)
            {
                _logger.LogError("{repoName} SqlException {error}", "OtpTypes Update", ex.Message);
                if (ex.Number.Equals(2627))
                {
                    returnValue.Code = 999;
                }
                else
                {
                    returnValue.Code = 998;
                }

                returnValue.Message = ex.ToString();
            }
            catch (Exception ex)
            {
                _logger.LogError("{repoName} Exception {error}", "OtpTypes", ex.Message);
                returnValue.Code = 404;
                returnValue.Message = ex.ToString();
            }

            return returnValue;
        }

        public async Task<DLResponse<bool>> DeleteAsync(OtpTypes value)
        {
            var returnValue = new DLResponse<bool>(false, "Success");
            try
            {
                _writeContext.OtpTypes.Remove(value);
                await _writeContext.SaveChangesAsync();
                returnValue.Value = true;
            }
            catch (SqlException ex)
            {
                _logger.LogError("{repoName} SqlException {error}", "OtpTypes Delete", ex.Message);
                if (ex.Number.Equals(2627))
                {
                    returnValue.Code = 999;
                }
                else
                {
                    returnValue.Code = 998;
                }

                returnValue.Message = ex.ToString();
            }
            catch (Exception ex)
            {
                _logger.LogError("{repoName} Exception {error}", "OtpTypes Delete", ex.Message);
                returnValue.Code = 404;
                returnValue.Message = ex.ToString();
            }

            return returnValue;
        }

        public async Task<DLResponse<OtpTypes>> GetByPkAsync(int id)
        {
            var returnValue = new DLResponse<OtpTypes>();
            try
            {
                var result =
                    from otp_types in _readContext.OtpTypes
                    where otp_types.Id.Equals(id)select otp_types;
                returnValue.Value = await result.FirstAsync();
                if (returnValue.Value == null)
                {
                    returnValue.Code = 404;
                    returnValue.Message = $"Not found in OtpTypes";
                    return returnValue;
                }
            }
            catch (Exception ex)
            {
                _logger.LogError("{repoName} Exception {error}", "OtpTypes GetByPk", ex.Message);
                returnValue.Code = 404;
                returnValue.Message = ex.ToString();
            }

            return returnValue;
        }

        public async Task<DLResponse<List<OtpTypes>>> ListAsync(int? pageNumber = null, int? pageSize = null)
        {
            var returnValue = new DLResponse<List<OtpTypes>>();
            try
            {
                if (pageNumber < 1)
                {
                    returnValue.Code = 404;
                    returnValue.Message = "Page Number must be greater than 1";
                }
                else
                {
                    if (pageNumber != null)
                    {
                        var skip = ((pageNumber - 1) * pageSize);
                        var take = pageSize;
                        returnValue.Value = await _readContext.OtpTypes.Skip(skip.Value).Take(take.Value).ToListAsync();
                    }
                    else
                    {
                        returnValue.Value = await _readContext.OtpTypes.ToListAsync();
                    }
                }
            }
            catch (Exception ex)
            {
                returnValue.Code = 404;
                returnValue.Message = ex.ToString();
            }

            return returnValue;
        }

        public async Task<DLResponse<int>> CountAsync()
        {
            var returnValue = new DLResponse<int>();
            try
            {
                returnValue.Value = await _readContext.OtpTypes.CountAsync();
            }
            catch (Exception ex)
            {
                returnValue.Code = 404;
                returnValue.Message = ex.ToString();
            }

            return returnValue;
        }

        public async Task<DLResponse<List<OtpTypesOtpMessagesRestResponseDto>>> OtpTypesOtpMessagesRestAsync(int otpTypesId)
        {
            var returnValue = new DLResponse<List<OtpTypesOtpMessagesRestResponseDto>>();
            try
            {
                var queryableResult =
                    from otp_messages in _readContext.OtpMessages
                    join otp_types in _readContext.OtpTypes on otp_messages.OtpTypeId equals otp_types.Id
                    where otp_types.Id.Equals(otpTypesId)select new OtpTypesOtpMessagesRestResponseDto()
                    {
                        Id = otp_messages.Id,
                        SmsSenderId = otp_messages.SmsSenderId,
                        OtpTypeId = otp_messages.OtpTypeId,
                        GsmNumber = otp_messages.GsmNumber,
                        OtpCode = otp_messages.OtpCode,
                        Message = otp_messages.Message,
                        ExpireSeconds = otp_messages.ExpireSeconds,
                        MessageDate = otp_messages.MessageDate,
                        MessageSid = otp_messages.MessageSid,
                        DailyCounter = otp_messages.DailyCounter
                    };
                var result = await queryableResult.ToListAsync();
                returnValue.Value = result;
            }
            catch (Exception ex)
            {
                _logger.LogError("{repoName} Exception {error}", "OtpTypes OtpTypesOtpMessagesRest", ex.Message);
                returnValue.Code = 404;
                returnValue.Message = ex.ToString();
            }

            return returnValue;
        }

        public async Task<DLResponse<OtpTypesOtpMessagesKeyRestResponseDto>> OtpTypesOtpMessagesKeyRestAsync(int otpTypesId, int otpMessagesId)
        {
            var returnValue = new DLResponse<OtpTypesOtpMessagesKeyRestResponseDto>();
            try
            {
                var queryableResult =
                    from otp_messages in _readContext.OtpMessages
                    join otp_types in _readContext.OtpTypes on otp_messages.OtpTypeId equals otp_types.Id
                    where otp_types.Id.Equals(otpTypesId) && otp_messages.Id.Equals(otpMessagesId)select new OtpTypesOtpMessagesKeyRestResponseDto()
                    {
                        Id = otp_messages.Id,
                        SmsSenderId = otp_messages.SmsSenderId,
                        OtpTypeId = otp_messages.OtpTypeId,
                        GsmNumber = otp_messages.GsmNumber,
                        OtpCode = otp_messages.OtpCode,
                        Message = otp_messages.Message,
                        ExpireSeconds = otp_messages.ExpireSeconds,
                        MessageDate = otp_messages.MessageDate,
                        MessageSid = otp_messages.MessageSid,
                        DailyCounter = otp_messages.DailyCounter
                    };
                var result = await queryableResult.FirstAsync();
                if (result == null)
                {
                    returnValue.Code = 404;
                    returnValue.Message = $"Not found in OtpTypes";
                }
                else
                {
                    returnValue.Value = result;
                }
            }
            catch (Exception ex)
            {
                _logger.LogError("{repoName} Exception {error}", "OtpTypes OtpTypesOtpMessagesKeyRest", ex.Message);
                returnValue.Code = 404;
                returnValue.Message = ex.ToString();
            }

            return returnValue;
        }
    }
}