// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuickCode.Demo.EmailManagerModule.Persistence.Contexts;

#nullable disable

namespace QuickCode.Demo.EmailManagerModule.Persistence.Migrations
{
    [DbContext(typeof(WriteDbContext))]
    [Migration("20241208220147_AutoMigration_638692920589349359")]
    partial class AutoMigration_638692920589349359
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuickCode.Demo.EmailManagerModule.Domain.Entities.CampaignMessages", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CampaignTypeId")
                        .HasColumnType("int")
                        .HasColumnName("CAMPAIGN_TYPE_ID");

                    b.Property<int>("DailyCounter")
                        .HasColumnType("int")
                        .HasColumnName("DAILY_COUNTER");

                    b.Property<DateTime?>("DeletedOnUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("DeletedOnUtc");

                    b.Property<int>("EmailSenderId")
                        .HasColumnType("int")
                        .HasColumnName("EMAIL_SENDER_ID");

                    b.Property<string>("GsmNumber")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("GSM_NUMBER");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<string>("Message")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("MESSAGE");

                    b.Property<DateTime>("MessageDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("MESSAGE_DATE")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("MessageSid")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("MESSAGE_SID");

                    b.HasKey("Id");

                    b.HasIndex("CampaignTypeId");

                    b.HasIndex("EmailSenderId");

                    b.HasIndex("IsDeleted")
                        .HasFilter("IsDeleted = 0");

                    b.ToTable("CAMPAIGN_MESSAGES");
                });

            modelBuilder.Entity("QuickCode.Demo.EmailManagerModule.Domain.Entities.CampaignTypes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DeletedOnUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("DeletedOnUtc");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<string>("Name")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("NAME");

                    b.Property<string>("Template")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("TEMPLATE");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted")
                        .HasFilter("IsDeleted = 0");

                    b.ToTable("CAMPAIGN_TYPES");
                });

            modelBuilder.Entity("QuickCode.Demo.EmailManagerModule.Domain.Entities.EmailSenders", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DeletedOnUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("DeletedOnUtc");

                    b.Property<string>("GsmNumber")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("GSM_NUMBER");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<string>("ProviderName")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("PROVIDER_NAME");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted")
                        .HasFilter("IsDeleted = 0");

                    b.ToTable("EMAIL_SENDERS");
                });

            modelBuilder.Entity("QuickCode.Demo.EmailManagerModule.Domain.Entities.InfoMessages", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DailyCounter")
                        .HasColumnType("int")
                        .HasColumnName("DAILY_COUNTER");

                    b.Property<DateTime?>("DeletedOnUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("DeletedOnUtc");

                    b.Property<int>("EmailSenderId")
                        .HasColumnType("int")
                        .HasColumnName("EMAIL_SENDER_ID");

                    b.Property<string>("GsmNumber")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("GSM_NUMBER");

                    b.Property<int>("InfoTypeId")
                        .HasColumnType("int")
                        .HasColumnName("INFO_TYPE_ID");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<string>("Message")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("MESSAGE");

                    b.Property<DateTime>("MessageDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("MESSAGE_DATE")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("MessageSid")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("MESSAGE_SID");

                    b.HasKey("Id");

                    b.HasIndex("EmailSenderId");

                    b.HasIndex("InfoTypeId");

                    b.HasIndex("IsDeleted")
                        .HasFilter("IsDeleted = 0");

                    b.ToTable("INFO_MESSAGES");
                });

            modelBuilder.Entity("QuickCode.Demo.EmailManagerModule.Domain.Entities.InfoTypes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DeletedOnUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("DeletedOnUtc");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<string>("Name")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("NAME");

                    b.Property<string>("Template")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("TEMPLATE");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted")
                        .HasFilter("IsDeleted = 0");

                    b.ToTable("INFO_TYPES");
                });

            modelBuilder.Entity("QuickCode.Demo.EmailManagerModule.Domain.Entities.OtpMessages", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DailyCounter")
                        .HasColumnType("int")
                        .HasColumnName("DAILY_COUNTER");

                    b.Property<DateTime?>("DeletedOnUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("DeletedOnUtc");

                    b.Property<int>("EmailSenderId")
                        .HasColumnType("int")
                        .HasColumnName("EMAIL_SENDER_ID");

                    b.Property<int>("ExpireSeconds")
                        .HasColumnType("int")
                        .HasColumnName("EXPIRE_SECONDS");

                    b.Property<string>("GsmNumber")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("GSM_NUMBER");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<string>("Message")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("MESSAGE");

                    b.Property<DateTime>("MessageDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("MESSAGE_DATE")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("MessageSid")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("MESSAGE_SID");

                    b.Property<string>("OtpCode")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("OTP_CODE");

                    b.Property<int>("OtpTypeId")
                        .HasColumnType("int")
                        .HasColumnName("OTP_TYPE_ID");

                    b.HasKey("Id");

                    b.HasIndex("EmailSenderId");

                    b.HasIndex("IsDeleted")
                        .HasFilter("IsDeleted = 0");

                    b.HasIndex("OtpTypeId");

                    b.ToTable("OTP_MESSAGES");
                });

            modelBuilder.Entity("QuickCode.Demo.EmailManagerModule.Domain.Entities.OtpTypes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DeletedOnUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("DeletedOnUtc");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<string>("Name")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("NAME");

                    b.Property<string>("Template")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("TEMPLATE");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted")
                        .HasFilter("IsDeleted = 0");

                    b.ToTable("OTP_TYPES");
                });

            modelBuilder.Entity("QuickCode.Demo.EmailManagerModule.Domain.Entities.CampaignMessages", b =>
                {
                    b.HasOne("QuickCode.Demo.EmailManagerModule.Domain.Entities.CampaignTypes", "CampaignType")
                        .WithMany("CampaignMessages")
                        .HasForeignKey("CampaignTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuickCode.Demo.EmailManagerModule.Domain.Entities.EmailSenders", "EmailSender")
                        .WithMany("CampaignMessages")
                        .HasForeignKey("EmailSenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CampaignType");

                    b.Navigation("EmailSender");
                });

            modelBuilder.Entity("QuickCode.Demo.EmailManagerModule.Domain.Entities.InfoMessages", b =>
                {
                    b.HasOne("QuickCode.Demo.EmailManagerModule.Domain.Entities.EmailSenders", "EmailSender")
                        .WithMany("InfoMessages")
                        .HasForeignKey("EmailSenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuickCode.Demo.EmailManagerModule.Domain.Entities.InfoTypes", "InfoType")
                        .WithMany("InfoMessages")
                        .HasForeignKey("InfoTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EmailSender");

                    b.Navigation("InfoType");
                });

            modelBuilder.Entity("QuickCode.Demo.EmailManagerModule.Domain.Entities.OtpMessages", b =>
                {
                    b.HasOne("QuickCode.Demo.EmailManagerModule.Domain.Entities.EmailSenders", "EmailSender")
                        .WithMany("OtpMessages")
                        .HasForeignKey("EmailSenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuickCode.Demo.EmailManagerModule.Domain.Entities.OtpTypes", "OtpType")
                        .WithMany("OtpMessages")
                        .HasForeignKey("OtpTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EmailSender");

                    b.Navigation("OtpType");
                });

            modelBuilder.Entity("QuickCode.Demo.EmailManagerModule.Domain.Entities.CampaignTypes", b =>
                {
                    b.Navigation("CampaignMessages");
                });

            modelBuilder.Entity("QuickCode.Demo.EmailManagerModule.Domain.Entities.EmailSenders", b =>
                {
                    b.Navigation("CampaignMessages");

                    b.Navigation("InfoMessages");

                    b.Navigation("OtpMessages");
                });

            modelBuilder.Entity("QuickCode.Demo.EmailManagerModule.Domain.Entities.InfoTypes", b =>
                {
                    b.Navigation("InfoMessages");
                });

            modelBuilder.Entity("QuickCode.Demo.EmailManagerModule.Domain.Entities.OtpTypes", b =>
                {
                    b.Navigation("OtpMessages");
                });
#pragma warning restore 612, 618
        }
    }
}
