//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.Demo.EmailManagerModule.Application.Models;
using QuickCode.Demo.EmailManagerModule.Domain.Entities;
using QuickCode.Demo.EmailManagerModule.Application.Interfaces.Repositories;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using QuickCode.Demo.EmailManagerModule.Persistence.Contexts;
using QuickCode.Demo.EmailManagerModule.Application.Dtos;

namespace QuickCode.Demo.EmailManagerModule.Persistence.Repositories
{
    public partial class InfoTypesRepository : IInfoTypesRepository
    {
        private readonly WriteDbContext _writeContext;
        private readonly ReadDbContext _readContext;
        private readonly ILogger<InfoTypesRepository> _logger;
        public InfoTypesRepository(ILogger<InfoTypesRepository> logger, WriteDbContext writeContext, ReadDbContext readContext)
        {
            _writeContext = writeContext;
            _readContext = readContext;
            _logger = logger;
        }

        public async Task<DLResponse<InfoTypes>> InsertAsync(InfoTypes value)
        {
            var returnValue = new DLResponse<InfoTypes>(value, "Not Defined");
            try
            {
                await _writeContext.InfoTypes.AddAsync(value);
                await _writeContext.SaveChangesAsync();
                returnValue.Value = value;
            }
            catch (SqlException ex)
            {
                _logger.LogError("{repoName} SqlException {error}", "InfoTypes Insert", ex.Message);
                if (ex.Number.Equals(2627))
                {
                    returnValue.Code = 999;
                    returnValue.Value = value;
                }
                else
                {
                    returnValue.Code = 998;
                    returnValue.Value = value;
                }

                returnValue.Message = ex.ToString();
            }
            catch (Exception ex)
            {
                _logger.LogError("{repoName} Exception {error}", "InfoTypes Insert", ex.Message);
                returnValue.Code = 500;
                returnValue.Value = value;
                returnValue.Message = ex.ToString();
            }

            return returnValue;
        }

        public async Task<DLResponse<bool>> UpdateAsync(InfoTypes value)
        {
            var returnValue = new DLResponse<bool>(false, "Success");
            try
            {
                _writeContext.Set<InfoTypes>().Update(value);
                await _writeContext.SaveChangesAsync();
                returnValue.Value = true;
            }
            catch (SqlException ex)
            {
                _logger.LogError("{repoName} SqlException {error}", "InfoTypes Update", ex.Message);
                if (ex.Number.Equals(2627))
                {
                    returnValue.Code = 999;
                }
                else
                {
                    returnValue.Code = 998;
                }

                returnValue.Message = ex.ToString();
            }
            catch (Exception ex)
            {
                _logger.LogError("{repoName} Exception {error}", "InfoTypes", ex.Message);
                returnValue.Code = 404;
                returnValue.Message = ex.ToString();
            }

            return returnValue;
        }

        public async Task<DLResponse<bool>> DeleteAsync(InfoTypes value)
        {
            var returnValue = new DLResponse<bool>(false, "Success");
            try
            {
                _writeContext.InfoTypes.Remove(value);
                await _writeContext.SaveChangesAsync();
                returnValue.Value = true;
            }
            catch (SqlException ex)
            {
                _logger.LogError("{repoName} SqlException {error}", "InfoTypes Delete", ex.Message);
                if (ex.Number.Equals(2627))
                {
                    returnValue.Code = 999;
                }
                else
                {
                    returnValue.Code = 998;
                }

                returnValue.Message = ex.ToString();
            }
            catch (Exception ex)
            {
                _logger.LogError("{repoName} Exception {error}", "InfoTypes Delete", ex.Message);
                returnValue.Code = 404;
                returnValue.Message = ex.ToString();
            }

            return returnValue;
        }

        public async Task<DLResponse<InfoTypes>> GetByPkAsync(int id)
        {
            var returnValue = new DLResponse<InfoTypes>();
            try
            {
                var result =
                    from info_types in _readContext.InfoTypes
                    where info_types.Id.Equals(id)select info_types;
                returnValue.Value = await result.FirstAsync();
                if (returnValue.Value == null)
                {
                    returnValue.Code = 404;
                    returnValue.Message = $"Not found in InfoTypes";
                    return returnValue;
                }
            }
            catch (Exception ex)
            {
                _logger.LogError("{repoName} Exception {error}", "InfoTypes GetByPk", ex.Message);
                returnValue.Code = 404;
                returnValue.Message = ex.ToString();
            }

            return returnValue;
        }

        public async Task<DLResponse<List<InfoTypes>>> ListAsync(int? pageNumber = null, int? pageSize = null)
        {
            var returnValue = new DLResponse<List<InfoTypes>>();
            try
            {
                if (pageNumber < 1)
                {
                    returnValue.Code = 404;
                    returnValue.Message = "Page Number must be greater than 1";
                }
                else
                {
                    if (pageNumber != null)
                    {
                        var skip = ((pageNumber - 1) * pageSize);
                        var take = pageSize;
                        returnValue.Value = await _readContext.InfoTypes.Skip(skip.Value).Take(take.Value).ToListAsync();
                    }
                    else
                    {
                        returnValue.Value = await _readContext.InfoTypes.ToListAsync();
                    }
                }
            }
            catch (Exception ex)
            {
                returnValue.Code = 404;
                returnValue.Message = ex.ToString();
            }

            return returnValue;
        }

        public async Task<DLResponse<int>> CountAsync()
        {
            var returnValue = new DLResponse<int>();
            try
            {
                returnValue.Value = await _readContext.InfoTypes.CountAsync();
            }
            catch (Exception ex)
            {
                returnValue.Code = 404;
                returnValue.Message = ex.ToString();
            }

            return returnValue;
        }

        public async Task<DLResponse<List<InfoTypesInfoMessagesRestResponseDto>>> InfoTypesInfoMessagesRestAsync(int infoTypesId)
        {
            var returnValue = new DLResponse<List<InfoTypesInfoMessagesRestResponseDto>>();
            try
            {
                var queryableResult =
                    from info_messages in _readContext.InfoMessages
                    join info_types in _readContext.InfoTypes on info_messages.InfoTypeId equals info_types.Id
                    where info_types.Id.Equals(infoTypesId)select new InfoTypesInfoMessagesRestResponseDto()
                    {
                        Id = info_messages.Id,
                        EmailSenderId = info_messages.EmailSenderId,
                        InfoTypeId = info_messages.InfoTypeId,
                        GsmNumber = info_messages.GsmNumber,
                        Message = info_messages.Message,
                        MessageDate = info_messages.MessageDate,
                        MessageSid = info_messages.MessageSid,
                        DailyCounter = info_messages.DailyCounter
                    };
                var result = await queryableResult.ToListAsync();
                returnValue.Value = result;
            }
            catch (Exception ex)
            {
                _logger.LogError("{repoName} Exception {error}", "InfoTypes InfoTypesInfoMessagesRest", ex.Message);
                returnValue.Code = 404;
                returnValue.Message = ex.ToString();
            }

            return returnValue;
        }

        public async Task<DLResponse<InfoTypesInfoMessagesKeyRestResponseDto>> InfoTypesInfoMessagesKeyRestAsync(int infoTypesId, int infoMessagesId)
        {
            var returnValue = new DLResponse<InfoTypesInfoMessagesKeyRestResponseDto>();
            try
            {
                var queryableResult =
                    from info_messages in _readContext.InfoMessages
                    join info_types in _readContext.InfoTypes on info_messages.InfoTypeId equals info_types.Id
                    where info_types.Id.Equals(infoTypesId) && info_messages.Id.Equals(infoMessagesId)select new InfoTypesInfoMessagesKeyRestResponseDto()
                    {
                        Id = info_messages.Id,
                        EmailSenderId = info_messages.EmailSenderId,
                        InfoTypeId = info_messages.InfoTypeId,
                        GsmNumber = info_messages.GsmNumber,
                        Message = info_messages.Message,
                        MessageDate = info_messages.MessageDate,
                        MessageSid = info_messages.MessageSid,
                        DailyCounter = info_messages.DailyCounter
                    };
                var result = await queryableResult.FirstAsync();
                if (result == null)
                {
                    returnValue.Code = 404;
                    returnValue.Message = $"Not found in InfoTypes";
                }
                else
                {
                    returnValue.Value = result;
                }
            }
            catch (Exception ex)
            {
                _logger.LogError("{repoName} Exception {error}", "InfoTypes InfoTypesInfoMessagesKeyRest", ex.Message);
                returnValue.Code = 404;
                returnValue.Message = ex.ToString();
            }

            return returnValue;
        }
    }
}