//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.Demo.UserManagerModule.Application.Models;
using QuickCode.Demo.UserManagerModule.Domain.Entities;
using QuickCode.Demo.UserManagerModule.Application.Dtos;
using System.Threading.Tasks;

namespace QuickCode.Demo.UserManagerModule.Application.Interfaces.Repositories
{
    public partial interface IKafkaEventsRepository : IBaseRepository<KafkaEvents>
    {
        Task<DLResponse<KafkaEvents>> GetByPkAsync(int id);
        Task<DLResponse<List<KafkaEventsGetKafkaEventsResponseDto>>> KafkaEventsGetKafkaEventsAsync();
        Task<DLResponse<List<KafkaEventsGetActiveKafkaEventsResponseDto>>> KafkaEventsGetActiveKafkaEventsAsync();
        Task<DLResponse<List<KafkaEventsGetTopicWorkflowsResponseDto>>> KafkaEventsGetTopicWorkflowsAsync(string kafkaEventsTopicName, string apiMethodDefinitionsHttpMethod);
        Task<DLResponse<List<KafkaEventsTopicWorkflows_RESTResponseDto>>> KafkaEventsTopicWorkflows_RESTAsync(int kafkaEventsId);
        Task<DLResponse<KafkaEventsTopicWorkflows_KEY_RESTResponseDto>> KafkaEventsTopicWorkflows_KEY_RESTAsync(int kafkaEventsId, int topicWorkflowsId);
    }
}