//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.Demo.UserManagerModule.Application.Models;
using QuickCode.Demo.UserManagerModule.Domain.Entities;
using QuickCode.Demo.UserManagerModule.Application.Interfaces.Repositories;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using QuickCode.Demo.UserManagerModule.Persistence.Contexts;
using QuickCode.Demo.UserManagerModule.Application.Dtos;

namespace QuickCode.Demo.UserManagerModule.Persistence.Repositories
{
    public partial class PortalPermissionsRepository : IPortalPermissionsRepository
    {
        private readonly WriteDbContext _writeContext;
        private readonly ReadDbContext _readContext;
        private readonly ILogger<PortalPermissionsRepository> _logger;
        public PortalPermissionsRepository(ILogger<PortalPermissionsRepository> logger, WriteDbContext writeContext, ReadDbContext readContext)
        {
            _writeContext = writeContext;
            _readContext = readContext;
            _logger = logger;
        }

        public async Task<DLResponse<PortalPermissions>> InsertAsync(PortalPermissions value)
        {
            var returnValue = new DLResponse<PortalPermissions>(value, "Not Defined");
            try
            {
                await _writeContext.PortalPermissions.AddAsync(value);
                await _writeContext.SaveChangesAsync();
                returnValue.Value = value;
            }
            catch (SqlException ex)
            {
                _logger.LogError("{repoName} SqlException {error}", "PortalPermissions Insert", ex.Message);
                if (ex.Number.Equals(2627))
                {
                    returnValue.Code = 999;
                    returnValue.Value = value;
                }
                else
                {
                    returnValue.Code = 998;
                    returnValue.Value = value;
                }

                returnValue.Message = ex.ToString();
            }
            catch (Exception ex)
            {
                _logger.LogError("{repoName} Exception {error}", "PortalPermissions Insert", ex.Message);
                returnValue.Code = 500;
                returnValue.Value = value;
                returnValue.Message = ex.ToString();
            }

            return returnValue;
        }

        public async Task<DLResponse<bool>> UpdateAsync(PortalPermissions value)
        {
            var returnValue = new DLResponse<bool>(false, "Success");
            try
            {
                _writeContext.Set<PortalPermissions>().Update(value);
                await _writeContext.SaveChangesAsync();
                returnValue.Value = true;
            }
            catch (SqlException ex)
            {
                _logger.LogError("{repoName} SqlException {error}", "PortalPermissions Update", ex.Message);
                if (ex.Number.Equals(2627))
                {
                    returnValue.Code = 999;
                }
                else
                {
                    returnValue.Code = 998;
                }

                returnValue.Message = ex.ToString();
            }
            catch (Exception ex)
            {
                _logger.LogError("{repoName} Exception {error}", "PortalPermissions", ex.Message);
                returnValue.Code = 404;
                returnValue.Message = ex.ToString();
            }

            return returnValue;
        }

        public async Task<DLResponse<bool>> DeleteAsync(PortalPermissions value)
        {
            var returnValue = new DLResponse<bool>(false, "Success");
            try
            {
                _writeContext.PortalPermissions.Remove(value);
                await _writeContext.SaveChangesAsync();
                returnValue.Value = true;
            }
            catch (SqlException ex)
            {
                _logger.LogError("{repoName} SqlException {error}", "PortalPermissions Delete", ex.Message);
                if (ex.Number.Equals(2627))
                {
                    returnValue.Code = 999;
                }
                else
                {
                    returnValue.Code = 998;
                }

                returnValue.Message = ex.ToString();
            }
            catch (Exception ex)
            {
                _logger.LogError("{repoName} Exception {error}", "PortalPermissions Delete", ex.Message);
                returnValue.Code = 404;
                returnValue.Message = ex.ToString();
            }

            return returnValue;
        }

        public async Task<DLResponse<PortalPermissions>> GetByPkAsync(int id)
        {
            var returnValue = new DLResponse<PortalPermissions>();
            try
            {
                var result =
                    from portal_permissions in _readContext.PortalPermissions
                    where portal_permissions.Id.Equals(id)select portal_permissions;
                returnValue.Value = await result.FirstAsync();
                if (returnValue.Value == null)
                {
                    returnValue.Code = 404;
                    returnValue.Message = $"Not found in PortalPermissions";
                    return returnValue;
                }
            }
            catch (Exception ex)
            {
                _logger.LogError("{repoName} Exception {error}", "PortalPermissions GetByPk", ex.Message);
                returnValue.Code = 404;
                returnValue.Message = ex.ToString();
            }

            return returnValue;
        }

        public async Task<DLResponse<List<PortalPermissions>>> ListAsync(int? pageNumber = null, int? pageSize = null)
        {
            var returnValue = new DLResponse<List<PortalPermissions>>();
            try
            {
                if (pageNumber < 1)
                {
                    returnValue.Code = 404;
                    returnValue.Message = "Page Number must be greater than 1";
                }
                else
                {
                    if (pageNumber != null)
                    {
                        var skip = ((pageNumber - 1) * pageSize);
                        var take = pageSize;
                        returnValue.Value = await _readContext.PortalPermissions.Skip(skip.Value).Take(take.Value).ToListAsync();
                    }
                    else
                    {
                        returnValue.Value = await _readContext.PortalPermissions.ToListAsync();
                    }
                }
            }
            catch (Exception ex)
            {
                returnValue.Code = 404;
                returnValue.Message = ex.ToString();
            }

            return returnValue;
        }

        public async Task<DLResponse<int>> CountAsync()
        {
            var returnValue = new DLResponse<int>();
            try
            {
                returnValue.Value = await _readContext.PortalPermissions.CountAsync();
            }
            catch (Exception ex)
            {
                returnValue.Code = 404;
                returnValue.Message = ex.ToString();
            }

            return returnValue;
        }

        public async Task<DLResponse<List<PortalPermissionsPortalPermissionGroups_RESTResponseDto>>> PortalPermissionsPortalPermissionGroups_RESTAsync(int portalPermissionsId)
        {
            var returnValue = new DLResponse<List<PortalPermissionsPortalPermissionGroups_RESTResponseDto>>();
            try
            {
                var queryableResult =
                    from portal_permission_groups in _readContext.PortalPermissionGroups
                    join portal_permissions in _readContext.PortalPermissions on portal_permission_groups.PortalPermissionId equals portal_permissions.Id
                    where portal_permissions.Id.Equals(portalPermissionsId)select new PortalPermissionsPortalPermissionGroups_RESTResponseDto()
                    {
                        Id = portal_permission_groups.Id,
                        PortalPermissionId = portal_permission_groups.PortalPermissionId,
                        PermissionGroupId = portal_permission_groups.PermissionGroupId,
                        PortalPermissionTypeId = portal_permission_groups.PortalPermissionTypeId
                    };
                var result = await queryableResult.ToListAsync();
                returnValue.Value = result;
            }
            catch (Exception ex)
            {
                _logger.LogError("{repoName} Exception {error}", "PortalPermissions PortalPermissionsPortalPermissionGroups_REST", ex.Message);
                returnValue.Code = 404;
                returnValue.Message = ex.ToString();
            }

            return returnValue;
        }

        public async Task<DLResponse<PortalPermissionsPortalPermissionGroups_KEY_RESTResponseDto>> PortalPermissionsPortalPermissionGroups_KEY_RESTAsync(int portalPermissionsId, int portalPermissionGroupsId)
        {
            var returnValue = new DLResponse<PortalPermissionsPortalPermissionGroups_KEY_RESTResponseDto>();
            try
            {
                var queryableResult =
                    from portal_permission_groups in _readContext.PortalPermissionGroups
                    join portal_permissions in _readContext.PortalPermissions on portal_permission_groups.PortalPermissionId equals portal_permissions.Id
                    where portal_permissions.Id.Equals(portalPermissionsId) && portal_permission_groups.Id.Equals(portalPermissionGroupsId)select new PortalPermissionsPortalPermissionGroups_KEY_RESTResponseDto()
                    {
                        Id = portal_permission_groups.Id,
                        PortalPermissionId = portal_permission_groups.PortalPermissionId,
                        PermissionGroupId = portal_permission_groups.PermissionGroupId,
                        PortalPermissionTypeId = portal_permission_groups.PortalPermissionTypeId
                    };
                var result = await queryableResult.FirstAsync();
                if (result == null)
                {
                    returnValue.Code = 404;
                    returnValue.Message = $"Not found in PortalPermissions";
                }
                else
                {
                    returnValue.Value = result;
                }
            }
            catch (Exception ex)
            {
                _logger.LogError("{repoName} Exception {error}", "PortalPermissions PortalPermissionsPortalPermissionGroups_KEY_REST", ex.Message);
                returnValue.Code = 404;
                returnValue.Message = ex.ToString();
            }

            return returnValue;
        }
    }
}