//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.Demo.UserManagerModule.Application.Models;
using QuickCode.Demo.UserManagerModule.Domain.Entities;
using QuickCode.Demo.UserManagerModule.Application.Interfaces.Repositories;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using QuickCode.Demo.UserManagerModule.Persistence.Contexts;
using QuickCode.Demo.UserManagerModule.Application.Dtos;

namespace QuickCode.Demo.UserManagerModule.Persistence.Repositories
{
    public partial class PortalPermissionGroupsRepository : IPortalPermissionGroupsRepository
    {
        private readonly WriteDbContext _writeContext;
        private readonly ReadDbContext _readContext;
        private readonly ILogger<PortalPermissionGroupsRepository> _logger;
        public PortalPermissionGroupsRepository(ILogger<PortalPermissionGroupsRepository> logger, WriteDbContext writeContext, ReadDbContext readContext)
        {
            _writeContext = writeContext;
            _readContext = readContext;
            _logger = logger;
        }

        public async Task<DLResponse<PortalPermissionGroups>> InsertAsync(PortalPermissionGroups value)
        {
            var returnValue = new DLResponse<PortalPermissionGroups>(value, "Not Defined");
            try
            {
                await _writeContext.PortalPermissionGroups.AddAsync(value);
                await _writeContext.SaveChangesAsync();
                returnValue.Value = value;
            }
            catch (SqlException ex)
            {
                _logger.LogError("{repoName} SqlException {error}", "PortalPermissionGroups Insert", ex.Message);
                if (ex.Number.Equals(2627))
                {
                    returnValue.Code = 999;
                    returnValue.Value = value;
                }
                else
                {
                    returnValue.Code = 998;
                    returnValue.Value = value;
                }

                returnValue.Message = ex.ToString();
            }
            catch (Exception ex)
            {
                _logger.LogError("{repoName} Exception {error}", "PortalPermissionGroups Insert", ex.Message);
                returnValue.Code = 500;
                returnValue.Value = value;
                returnValue.Message = ex.ToString();
            }

            return returnValue;
        }

        public async Task<DLResponse<bool>> UpdateAsync(PortalPermissionGroups value)
        {
            var returnValue = new DLResponse<bool>(false, "Success");
            try
            {
                _writeContext.Set<PortalPermissionGroups>().Update(value);
                await _writeContext.SaveChangesAsync();
                returnValue.Value = true;
            }
            catch (SqlException ex)
            {
                _logger.LogError("{repoName} SqlException {error}", "PortalPermissionGroups Update", ex.Message);
                if (ex.Number.Equals(2627))
                {
                    returnValue.Code = 999;
                }
                else
                {
                    returnValue.Code = 998;
                }

                returnValue.Message = ex.ToString();
            }
            catch (Exception ex)
            {
                _logger.LogError("{repoName} Exception {error}", "PortalPermissionGroups", ex.Message);
                returnValue.Code = 404;
                returnValue.Message = ex.ToString();
            }

            return returnValue;
        }

        public async Task<DLResponse<bool>> DeleteAsync(PortalPermissionGroups value)
        {
            var returnValue = new DLResponse<bool>(false, "Success");
            try
            {
                _writeContext.PortalPermissionGroups.Remove(value);
                await _writeContext.SaveChangesAsync();
                returnValue.Value = true;
            }
            catch (SqlException ex)
            {
                _logger.LogError("{repoName} SqlException {error}", "PortalPermissionGroups Delete", ex.Message);
                if (ex.Number.Equals(2627))
                {
                    returnValue.Code = 999;
                }
                else
                {
                    returnValue.Code = 998;
                }

                returnValue.Message = ex.ToString();
            }
            catch (Exception ex)
            {
                _logger.LogError("{repoName} Exception {error}", "PortalPermissionGroups Delete", ex.Message);
                returnValue.Code = 404;
                returnValue.Message = ex.ToString();
            }

            return returnValue;
        }

        public async Task<DLResponse<PortalPermissionGroups>> GetByPkAsync(int id)
        {
            var returnValue = new DLResponse<PortalPermissionGroups>();
            try
            {
                var result =
                    from portal_permission_groups in _readContext.PortalPermissionGroups
                    where portal_permission_groups.Id.Equals(id)select portal_permission_groups;
                returnValue.Value = await result.FirstAsync();
                if (returnValue.Value == null)
                {
                    returnValue.Code = 404;
                    returnValue.Message = $"Not found in PortalPermissionGroups";
                    return returnValue;
                }
            }
            catch (Exception ex)
            {
                _logger.LogError("{repoName} Exception {error}", "PortalPermissionGroups GetByPk", ex.Message);
                returnValue.Code = 404;
                returnValue.Message = ex.ToString();
            }

            return returnValue;
        }

        public async Task<DLResponse<List<PortalPermissionGroups>>> ListAsync(int? pageNumber = null, int? pageSize = null)
        {
            var returnValue = new DLResponse<List<PortalPermissionGroups>>();
            try
            {
                if (pageNumber < 1)
                {
                    returnValue.Code = 404;
                    returnValue.Message = "Page Number must be greater than 1";
                }
                else
                {
                    if (pageNumber != null)
                    {
                        var skip = ((pageNumber - 1) * pageSize);
                        var take = pageSize;
                        returnValue.Value = await _readContext.PortalPermissionGroups.Skip(skip.Value).Take(take.Value).ToListAsync();
                    }
                    else
                    {
                        returnValue.Value = await _readContext.PortalPermissionGroups.ToListAsync();
                    }
                }
            }
            catch (Exception ex)
            {
                returnValue.Code = 404;
                returnValue.Message = ex.ToString();
            }

            return returnValue;
        }

        public async Task<DLResponse<int>> CountAsync()
        {
            var returnValue = new DLResponse<int>();
            try
            {
                returnValue.Value = await _readContext.PortalPermissionGroups.CountAsync();
            }
            catch (Exception ex)
            {
                returnValue.Code = 404;
                returnValue.Message = ex.ToString();
            }

            return returnValue;
        }

        public async Task<DLResponse<List<PortalPermissionGroupsGetPortalPermissionGroupsResponseDto>>> PortalPermissionGroupsGetPortalPermissionGroupsAsync(int portalPermissionGroupsPermissionGroupId)
        {
            var returnValue = new DLResponse<List<PortalPermissionGroupsGetPortalPermissionGroupsResponseDto>>();
            try
            {
                var queryableResult =
                    from portal_permission_groups in _readContext.PortalPermissionGroups
                    where portal_permission_groups.PermissionGroupId.Equals(portalPermissionGroupsPermissionGroupId)select new PortalPermissionGroupsGetPortalPermissionGroupsResponseDto()
                    {
                        Id = portal_permission_groups.Id,
                        PortalPermissionId = portal_permission_groups.PortalPermissionId,
                        PermissionGroupId = portal_permission_groups.PermissionGroupId,
                        PortalPermissionTypeId = portal_permission_groups.PortalPermissionTypeId
                    };
                var result = await queryableResult.ToListAsync();
                returnValue.Value = result;
            }
            catch (Exception ex)
            {
                _logger.LogError("{repoName} Exception {error}", "PortalPermissionGroups PortalPermissionGroupsGetPortalPermissionGroups", ex.Message);
                returnValue.Code = 404;
                returnValue.Message = ex.ToString();
            }

            return returnValue;
        }

        public async Task<DLResponse<List<PortalPermissionGroupsGetPortalPermissionGroupResponseDto>>> PortalPermissionGroupsGetPortalPermissionGroupAsync(int portalPermissionGroupsPortalPermissionId, int portalPermissionGroupsPermissionGroupId, int portalPermissionGroupsPortalPermissionTypeId)
        {
            var returnValue = new DLResponse<List<PortalPermissionGroupsGetPortalPermissionGroupResponseDto>>();
            try
            {
                var queryableResult =
                    from portal_permission_groups in _readContext.PortalPermissionGroups
                    where portal_permission_groups.PortalPermissionId.Equals(portalPermissionGroupsPortalPermissionId) && portal_permission_groups.PermissionGroupId.Equals(portalPermissionGroupsPermissionGroupId) && portal_permission_groups.PortalPermissionTypeId.Equals(portalPermissionGroupsPortalPermissionTypeId)select new PortalPermissionGroupsGetPortalPermissionGroupResponseDto()
                    {
                        Id = portal_permission_groups.Id,
                        PortalPermissionId = portal_permission_groups.PortalPermissionId,
                        PermissionGroupId = portal_permission_groups.PermissionGroupId,
                        PortalPermissionTypeId = portal_permission_groups.PortalPermissionTypeId
                    };
                var result = await queryableResult.ToListAsync();
                returnValue.Value = result;
            }
            catch (Exception ex)
            {
                _logger.LogError("{repoName} Exception {error}", "PortalPermissionGroups PortalPermissionGroupsGetPortalPermissionGroup", ex.Message);
                returnValue.Code = 404;
                returnValue.Message = ex.ToString();
            }

            return returnValue;
        }
    }
}