//------------------------------------------------------------------------------  
// <auto-generated>                                                               
// This code was generated by QuickCode.                                          
// Runtime Version:1.0                                                            
//                                                                                
// Changes to this file may cause incorrect behavior and will be lost if          
// the code is regenerated.                                                       
// </auto-generated>                                                              
//------------------------------------------------------------------------------  
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;

namespace QuickCode.Demo.UserManagerModule.Application.Dtos
{
    public record PortalMenusDto
    {
        public int Id { get; init; }
        public string Name { get; init; }
        public string Text { get; init; }
        public string Tooltip { get; init; }
        public string ActionName { get; init; }
        public int OrderNo { get; init; }
        public string ParentName { get; init; }
        public string ItemType { get; init; }
    }
}