//------------------------------------------------------------------------------  
// <auto-generated>                                                               
// This code was generated by QuickCode.                                          
// Runtime Version:1.0                                                            
//                                                                                
// Changes to this file may cause incorrect behavior and will be lost if          
// the code is regenerated.                                                       
// </auto-generated>                                                              
//------------------------------------------------------------------------------  
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;

namespace QuickCode.Demo.UserManagerModule.Persistence.Models.Dto
{

    public class PortalLoginResponse
    {

        public Int32 Id { get; set; } //ID

        public Int32 GroupId { get; set; } //GROUP_ID

        public String Name { get; set; } //NAME

        public String Surname { get; set; } //SURNAME

        public String Username { get; set; } //USERNAME

        public String Email { get; set; } //EMAIL

        public String Gsm { get; set; } //GSM

    }



    public class PortalLoginRequest
    {
        public String Username { get; set; }

        public String Password { get; set; }
    }


}
